### ISSUE TITLE
Minimal example from README doens't work

### ISSUE THREAD

**Issue by micalevisk** [gr2m/get-json-paths-action#9]
When I tried to use the following workflow
```yml
name: Minimal example   ## fixed 'Name' typo 
on: [push]

jobs:
  minimal_example:
    runs-on: ubuntu-latest
    steps:
      - id: action_with_json_output
        run: 'echo ::set-output name=data::{ "foo": { "bar":"baz" } }'
      - id: data
        uses: gr2m/get-json-paths-action@v1.x
        with:
          json: ${{ steps.action_with_json_output.outputs.data }}
          bar: "foo.bar"
      - run: "echo bar is ${{ steps.data.outputs.bar }}"
```
I got the error `SyntaxError: Unexpected token f in JSON at position 2` because the `steps.action_with_json_output.outputs.data` value is the string `'{ foo: { bar:baz } }'`
![output](https://user-images.githubusercontent.com/13461315/76169466-d3fae500-614e-11ea-96be-1044cbdcf6c9.png)

---

To fix this I just change the `data` output to `{ \"foo\": { \"bar\":\"baz\" } }`.

Actually I think in the line below `value` should be stringified because the second param of `setOutput` is expected to be a string
https://github.com/gr2m/get-json-paths-action/blob/1ded8f388247a1d62f74718206877cd75d961ac9/index.js#L14-L16
